package com.runescape.content.skills.cooking;

import com.runescape.logic.utility.rsconfigs.RSItems;

public enum CookData {
    /**
     * Fish
     */
	SHRIMP(1, 30.0, 128, 512, RSItems.RAW_SHRIMPS, RSItems.BURNT_FISH, RSItems.SHRIMPS),
	CRAY_FISH(1, 30.0, 128, 512, RSItems.RAW_CRAYFISH, RSItems.BURNT_CRAYFISH, RSItems.CRAYFISH),
	ANCHOVIES(1, 30.0, 128, 512, RSItems.RAW_ANCHOVIES, RSItems.BURNT_FISH, RSItems.ANCHOVIES),
	SARDINE(1, 30.0, 128, 512, RSItems.RAW_SARDINE, RSItems.BURNT_FISH_369, RSItems.SARDINE),
	HERRING(5, 50.0, 108, 472, RSItems.RAW_HERRING, RSItems.BURNT_FISH_357, RSItems.HERRING),
	MACKEREL(10, 60.0, 98, 452, RSItems.RAW_MACKEREL, RSItems.BURNT_FISH_357, RSItems.MACKEREL),
	TROUT(15, 70.0, 88, 432, RSItems.RAW_TROUT, RSItems.BURNT_FISH_343, RSItems.TROUT),
	COD(18, 75.0, 88, 432, RSItems.RAW_COD, RSItems.BURNT_FISH_343, RSItems.COD),
	PIKE(20, 80.0, 78, 412, RSItems.RAW_PIKE, RSItems.BURNT_FISH_343, RSItems.PIKE),
	SALMON(25, 90.0, 68, 392, RSItems.RAW_SALMON, RSItems.BURNT_FISH_343, RSItems.SALMON),
	TUNA(30, 100.0, 58, 372, RSItems.RAW_TUNA, RSItems.BURNT_FISH_367, RSItems.TUNA),
	LOBSTER(40, 120.0, 38, 332, RSItems.RAW_LOBSTER, RSItems.BURNT_LOBSTER, RSItems.LOBSTER),
	BASS(43, 130.0, 33, 312, RSItems.RAW_BASS, RSItems.BURNT_FISH_367, RSItems.BASS),
	SWORDFISH(45, 140.0, 18, 292, RSItems.RAW_SWORDFISH, RSItems.BURNT_SWORDFISH, RSItems.SWORDFISH),
	MONKFISH(62, 150.0, 13, 280, RSItems.RAW_MONKFISH, RSItems.BURNT_MONKFISH, RSItems.MONKFISH),
	SHARK(80, 210.0, 1, 232, RSItems.RAW_SHARK, RSItems.BURNT_SHARK, RSItems.SHARK),
	SEA_TURTLE(82, 211.0, 1, 222, RSItems.RAW_SEA_TURTLE, RSItems.BURNT_SEA_TURTLE, RSItems.SEA_TURTLE),
	MANTA_RAY(91, 216.3, 1, 222, RSItems.RAW_MANTA_RAY, RSItems.BURNT_MANTA_RAY, RSItems.MANTA_RAY),
	CAVEFISH(88, 214.0, 1, 232, RSItems.RAW_CAVEFISH, RSItems.BURNT_CAVEFISH, RSItems.CAVEFISH),
	ROCKTAIL(93, 225.0, 1, 222, RSItems.RAW_ROCKTAIL, RSItems.BURNT_ROCKTAIL, RSItems.ROCKTAIL),
	CAVE_EEL(38, 115.0, 38, 332, RSItems.RAW_CAVE_EEL, RSItems.BURNT_CAVE_EEL, RSItems.CAVE_EEL),
	SLIMY_EEL(28, 95.0, 63, 382, RSItems.SLIMY_EEL, RSItems.BURNT_EEL, RSItems.COOKED_SLIMY_EEL),
	RAINBOW_FISH(35, 110.0, 56, 370, RSItems.RAW_RAINBOW_FISH, RSItems.BURNT_RAINBOW_FISH, RSItems.RAINBOW_FISH),
	THIN_SNAIL(12, 70.0, 93, 444, RSItems.THIN_SNAIL, RSItems.BURNT_SNAIL, RSItems.THIN_SNAIL),
	LEAN_SNAIL(17, 80.0, 93, 444, RSItems.LEAN_SNAIL, RSItems.BURNT_SNAIL, RSItems.LEAN_SNAIL_MEAT),
	FAT_SNAIL(22, 95.0, 73, 402, RSItems.FAT_SNAIL, RSItems.BURNT_SNAIL, RSItems.FAT_SNAIL_MEAT),
	/**
	 * Bread
	 */
	BREAD(1, 40.0, 118, 492, RSItems.BREAD_DOUGH, RSItems.BURNT_BREAD, RSItems.BREAD),
	PITTA_BREAD(58, 40.0, 118, 492, RSItems.PITTA_DOUGH, RSItems.BURNT_PITTA_BREAD, RSItems.PITTA_BREAD),
	/**
	 * Pies
	 */
	REDBERRY_PIE(10, 78.0, 98, 452, RSItems.UNCOOKED_BERRY_PIE, RSItems.BURNT_PIE, RSItems.REDBERRY_PIE), 
	MEAT_PIE(20, 110.0, 78, 412, RSItems.UNCOOKED_MEAT_PIE, RSItems.BURNT_PIE, RSItems.MEAT_PIE), 
	MUD_PIE(29, 128.0, 58, 372, RSItems.RAW_MUD_PIE, RSItems.BURNT_PIE, RSItems.MUD_PIE), 
	APPLE_PIE(30, 130.0, 58, 372, RSItems.UNCOOKED_APPLE_PIE, RSItems.BURNT_PIE, RSItems.APPLE_PIE),
	GARDEN_PIE(34, 138.0, 48, 352, RSItems.RAW_GARDEN_PIE, RSItems.BURNT_PIE, RSItems.GARDEN_PIE),
	FISH_PIE(47, 164.0, 38, 332, RSItems.RAW_FISH_PIE, RSItems.BURNT_PIE, RSItems.FISH_PIE),
	ADMIRAL_PIE(70, 210.0, 15, 270, RSItems.RAW_ADMIRAL_PIE, RSItems.BURNT_PIE, RSItems.ADMIRAL_PIE), 
	WILD_PIE(85, 240.0, 1, 222, RSItems.RAW_WILD_PIE, RSItems.BURNT_PIE, RSItems.WILD_PIE), 
	SUMMER_PIE(95, 260.0, 1, 212, RSItems.RAW_SUMMER_PIE, RSItems.BURNT_PIE, RSItems.SUMMER_PIE),
	/**
	 * Others
	 */
	STEW(25, 117.0, 68, 392, RSItems.UNCOOKED_STEW, RSItems.BURNT_STEW, RSItems.STEW), 
	CURRY(25, 117.0, 68, 392, RSItems.UNCOOKED_CURRY, RSItems.BURNT_CURRY, RSItems.CURRY), 
	BAKED_POTATO(7, 15.0, 108, 472, RSItems.POTATO, RSItems.BURNT_POTATO, RSItems.BAKED_POTATO),
	SCRAMBLED_EGG(13, 50.0, 90, 438, RSItems.UNCOOKED_EGG, RSItems.BURNT_EGG, RSItems.SCRAMBLED_EGG),
	COOKED_SWEETCORN(28, 104.0, 78, 412, RSItems.SWEETCORN, RSItems.BURNT_SWEETCORN, RSItems.COOKED_SWEETCORN),
	FRIED_ONIONS(42, 60.0, 36, 322, RSItems.CHOPPED_ONION, RSItems.BURNT_ONION, RSItems.FRIED_ONIONS),
	FRIED_MUSHROOMS(46, 60.0, 16, 282, RSItems.SLICED_MUSHROOMS, RSItems.BURNT_MUSHROOM, RSItems.FRIED_MUSHROOMS), 
	PLAIN_PIZZA(35, 143.0, 48, 352, RSItems.UNCOOKED_PIZZA, RSItems.BURNT_PIZZA, RSItems.PLAIN_PIZZA),
	RABBIT(1, 30.0, 128, 512, RSItems.RAW_RABBIT, RSItems.BURNT_RABBIT, RSItems.COOKED_RABBIT), 
	CHICKEN(1, 30.0, 128, 512, RSItems.RAW_CHICKEN, RSItems.BURNT_CHICKEN, RSItems.COOKED_CHICKEN),
	BEEF(1, 30.0, 128, 512, RSItems.RAW_BEEF, RSItems.BURNT_MEAT, RSItems.COOKED_MEAT), 
	BEAR(1, 30.0, 128, 512, RSItems.RAW_BEAR_MEAT, RSItems.BURNT_MEAT, RSItems.COOKED_MEAT), 
	RAT(1, 30.0, 128, 512, RSItems.RAW_RAT_MEAT, RSItems.BURNT_MEAT, RSItems.COOKED_MEAT), 
	UGTHANKI(1, 40.0, 30, 253, RSItems.RAW_UGTHANKI_MEAT, RSItems.BURNT_MEAT, RSItems.UGTHANKI_MEAT), 
	YAK(1, 30.0, 128, 512, RSItems.RAW_YAK_MEAT, RSItems.BURNT_MEAT, RSItems.COOKED_MEAT);

	public final byte level;
	public final double xp;
    public final int lowChance;  // chance at level 1
    public final int highChance; // chance at level 99
	public final short rawId, burnId, cookId;
    	
    	CookData(int reqLevel, double xp, int lowChance, int highChance, int rawId, int burnId, int cookId) {
    		this.level = (byte) reqLevel;
    		this.xp = xp;
            this.lowChance = lowChance;
            this.highChance = highChance;
            this.rawId = (short) rawId;
            this.burnId = (short) burnId;
            this.cookId = (short) cookId;
    }

    public static CookData get(int itemId) {
        for(CookData data : CookData.values()) {
            if(data.rawId == itemId)
                return data;
        }
        return null;
    }

}
